class ResourceType:
    URL = "url"
    TEXT = "text"
    PDF = "pdf"
    IMAGE = "image"
    VIDEO = "video"
    AUDIO = "audio"
    HTML = "html"
    MARKDOWN = "markdown"
    CSV = "csv"
    JSON = "json"
    XML = "xml"
    ZIP = "zip"
    DOC = "doc"
    DOCX = "docx"
    XLS = "xls"
    XLSX = "xlsx"
    PPT = "ppt"
    PPTX = "pptx"

class ExtractedContentType:
    PLAIN_TEXT = "plain_text"
    HTML = "html"
    MARKDOWN = "markdown"
    JSON = "json"
    CSV = "csv"
    XML = "xml"
    PDF_TEXT = "pdf_text"
    IMAGE_TEXT = "image_text"
    AUDIO_TRANSCRIPT = "audio_transcript"
    VIDEO_TRANSCRIPT = "video_transcript"
    DOC_TEXT = "doc_text"
    DOCX_TEXT = "docx_text"
    XLS_TEXT = "xls_text"
    XLSX_TEXT = "xlsx_text"
    PPT_TEXT = "ppt_text"
    PPTX_TEXT = "pptx_text"