# Generated by Django 5.1 on 2024-08-24 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_format', models.CharField(blank=True, null=True)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('stop', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('mirostat', models.FloatField(default=False)),
                ('mirostat_eta', models.FloatField(blank=True, null=True)),
                ('mirostat_tau', models.FloatField(blank=True, null=True)),
                ('top_k', models.IntegerField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('min_p', models.FloatField(blank=True, null=True)),
                ('frequency_penalty', models.FloatField(blank=True, null=True)),
                ('repeat_last_n', models.IntegerField(blank=True, null=True)),
                ('tfs_z', models.FloatField(blank=True, null=True)),
                ('context_length', models.IntegerField(blank=True, null=True)),
                ('batch_size', models.IntegerField(blank=True, null=True)),
                ('tokens_to_keep_on_context_refresh', models.IntegerField(blank=True, null=True)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('use_mmap', models.BooleanField(default=False)),
                ('use_mlock', models.BooleanField(default=False)),
                ('num_thread', models.IntegerField(blank=True, null=True)),
                ('logit_bias', models.JSONField(blank=True, null=True)),
                ('logprobs', models.BooleanField(default=False)),
                ('top_logprobs', models.IntegerField(blank=True, null=True)),
                ('stream', models.BooleanField(blank=True, null=True)),
                ('tool_choice', models.CharField(blank=True, default='none', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('variables', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('name', models.CharField(blank=True, null=True)),
                ('properties', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='components.llmproperties')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables_values', models.JSONField()),
                ('generated_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.promptcategory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.prompttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PromptPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_value', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.prompt')),
            ],
        ),
    ]
